[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"
    X-Frame-Options = "ALLOW-FROM *"
    Content-Security-Policy = "frame-ancestors 'self' *"
    Cross-Origin-Embedder-Policy = "require-corp"
